### ISSUE TITLE
Is possible to use this with CoffeeScript

### ISSUE THREAD

**Issue by Jeremi360** [GodotExplorer/ECMAScript#111]
I always wanted to try [CoffeeScript] with godot.
[CoffeeScript] is compiled to JS, so it should be possible.

[CoffeeScript]: https://coffeescript.org
If this is possible can you give an example how ?

**Comment by Jeremi360** [comment]
> 可以参考typescript代码的使用。

Sorry @scgm0 , but I don't understand Japanese.

**Comment by greenbas** [comment]
They're speaking chinese, and according to deepL, they're asking you to refer to how typescript is used to use coffeescript. 

If you can set things up so that the coffeescript files are compiled to js before godot goes to use them, then it can work.

**Comment by Jeremi360** [comment]
> They're speaking chinese, and according to deepL, they're asking you to refer to how typescript is used to use coffeescript.
> 
> If you can set things up so that the coffeescript files are compiled to js before godot goes to use them, then it can work.

Okey I see thanks @greenbas
