### ISSUE TITLE
Problem when instantiating image

### ISSUE THREAD

**Issue by Klaider** [GodotExplorer/ECMAScript#113]
### Problem

I tried importing an image instance in different ways:
- `import image from 'res://img/img.png';`
- `import Image from 'res://img/img.png'; let image = Image.instance();`
- `import Image from 'res://img/img.png'; let image = new Image;`
- `let image = await import('res://img/img.png');`

None of these ways allow to show the image and, in some cases, code is not fully executed (using `console.log()`).

### Editor version

3.2.3

### How to reproduce

- Clone repository: https://github.com/Klaider/GdesBug000
- Play with `states/InitialState.jsx` scene

Involved code:

```js
import RecoyxLogo from 'res://img/company-logo/recoyx.png';

export default class InitialState extends godot.Node2D {
	constructor() {
		super();
	}

	async _ready() {
		await godot.yield(this.get_tree(), 'idle_frame');
		console.log('a');
		let recoyxLogo = RecoyxLogo;
		console.log('b');
		recoyxLogo.position = new godot.Vector2(0, 0);
		console.log('c');
		this.add_child(recoyxLogo);
		console.log('d');
		console.log(recoyxLogo);
	}

	_process(delta) {
	}
}
```

**Comment by Geequlim** [comment]
What is the `console.log(RecoyxLogo )` ?

**Comment by Klaider** [comment]
It logs `[StreamTexture:1189]`.

**Comment by Geequlim** [comment]
You don't need to instantiate the image. Just use it as an instantiated instance.

**Comment by Klaider** [comment]
Yeah, I tried it, as stated on the top of my issue... Nothing is drawn on the screen and some logs don't occur...

**Comment by Geequlim** [comment]
You'd better learn how to use godot first.

**Comment by Klaider** [comment]
My code is correct, I didn't try to do the same in GDScript, though.

**Comment by Geequlim** [comment]
No it is not an issue. `[StreamTexture:1189]` is a resource not a node.

**Comment by Klaider** [comment]
That makes sense, but why doesn't `console.log()` occur or why is not an error thrown and logged in the debugger console?

**Comment by Klaider** [comment]
I mean, if the last `console.log()` doesn't happen, then some error should have been thrown.

**Comment by Klaider** [comment]
Now code fully works, but I still don't understand why it was silent.
