### ISSUE TITLE
call_method: JavaScript Error not a function

### ISSUE THREAD

**Issue by Terria028** [GodotExplorer/ECMAScript#121]
I can't seems to use any godot function in this latest version of this module (alpha15)
My code was simply is this:

```
export default class SomeNode extends godot.Node2D {
// There is some code above here, but its not important

	_ready() {
		// Same thing happens with this.get_node('Sprite')
		this.sprite = this.$("Sprite");
		godot.print("hello world");
	}
}
```

And I get this error:
![image](https://user-images.githubusercontent.com/86240437/162875918-60fbc6ba-eddc-4bdf-b158-e0e5dd04c31d.png)

**Comment by Geequlim** [comment]
@zw7u9tru  Can you check this ?
I didn't compile and test your code before merge.

**Comment by XVhc6A** [comment]
Yes I will work on this right now

**Comment by antharuu** [comment]
Same problem

**Comment by zw7u9tru** [comment]
@Terria028 @antharuu  let me know if the current release works better for you!

**Comment by antharuu** [comment]
> @Terria028 @antharuu let me know if the current release works better for you!

Oh, thank you, it's good now !

**Comment by Terria028** [comment]
> @Terria028 @antharuu  let me know if the current release works better for you!

Yes, it is now fixed! Thank you, might close the issue now
