### ISSUE TITLE
Crashes if _input or _unhandled_input is present

### ISSUE THREAD

**Issue by vonagam** [GodotExplorer/ECMAScript#13]
On my machine playing scene crashes if i have a js class with `_input` or `_unhandled_input`.

Reproduction: create empty project, create some root node, attach new ecma script to it and add `_input(event) {}` or `_unhandled_input(even) {}`. Play the scene and move a mouse few seconds. 

Without those methods everything is working, as soon as i add them, crashes  appear. On crashes i can see messages about `malloc` in terminal with godot editor process.

Is this reproducible on your machine?

**Comment by domis4** [comment]
i can reproduce this using
```js
export default class Example extends godot.KinematicBody {
  _input() {}
}
```

Im using
- Godot `e707b712e8`
-  ECMAScript `ec69d88`
on mac os 10.15.4 (19E266)

**Comment by Geequlim** [comment]
I can't reproduce this problem

### Test case1

```js
_input() {
    console.log(arguments);
}
```
Output
```
[object Arguments]
```

### Test case2
```js
_input(event) {
    console.log(event);
}
	
_unhandled_input(event) {
    console.log(event);	
}
```

Output
```
[InputEventKey:1620]
[InputEventKey:1620]
```

**Comment by vonagam** [comment]
I am on mac as domis is. Maybe it is a platform specific issue?

**Comment by vonagam** [comment]
Works now.

**Comment by mikolajserediuk** [comment]
The issue is happening to me on v0.0.17. The same steps to reproduce as  before:
```
export default class Example extends godot.Node{
  _input() {}
}
```
Tested on both windows and linux builds. On windows 11 it crashes with no logs (even in verbose mode), on latest fedora - the IDE just freeze.
