### ISSUE TITLE
godot.randi() can return negative numbers

### ISSUE THREAD

**Issue by drusin** [GodotExplorer/ECMAScript#18]
According to the documentation, `randi()` should return a random integer between 0 and 2^32-1 which should make it trivial to get a random number in an interval via modulo.
`godot.randi()` can return negative values (I would assume between -2^16 and 2^16-1?) which forces you to wrap calls with `godot.floor()`.

**Comment by Geequlim** [comment]
I don't think I did anything different for any bultin functions.

**Comment by nhydock** [comment]
This is just a problem with javascript not having native unsigned int support by default, which is what godot is returning from randi.  Normally you would use js-ctypes if you wanted to have supported bindings to c/c++ datatypes

**Comment by Geequlim** [comment]
@drusin Can you try the latest version fixed the issue ?
You can download the precompiled binary file from the release page.

**Comment by Geequlim** [comment]
Should be fix as we are using 64bit integer now
