### ISSUE TITLE
Editor crashes when importing an ogg file

### ISSUE THREAD

**Issue by drusin** [GodotExplorer/ECMAScript#20]
Try to import an ogg file or to open a project with an ogg file. This crahes the editor on my system (Window 10 professional) with the following error in the console:
```
Assertion failed: f->temp_offset == f->alloc.alloc_buffer_length_in_bytes, file thirdparty/misc/stb_vorbis.c, line 4160
```

**Comment by Geequlim** [comment]
I don't think this is releated to the JavaScript binding
