### ISSUE TITLE
velocity = godot.Vector3(0,0,0); //This crash the scene, please help thanks.

### ISSUE THREAD

**Issue by BracerJack** [GodotExplorer/ECMAScript#28]
export default class Ball extends godot.KinematicBody
{
	
	// Declare member variables here. Examples:
	a = 2;
	b = "text";

	velocity = godot.Vector3(0,0,0); //This crash the scene, please help thanks.
	
	constructor()
	{
		super();
	}
	
	_ready()
	{
		
	}
	
	_process(delta)
	{

	}
	
	_physics_process(delta)
	{

	}
}

**Comment by Geequlim** [comment]
You should really learn JavaScript before starting making a game with this.

**Comment by Geequlim** [comment]
Thank you for making this report of crash case.

**Comment by BracerJack** [comment]
"You should really learn JavaScript before starting making a game with this."
I am sorry for offending you for asking a question.

How is this giving error:
velocity = godot.Vector3(0,0,0);

**Comment by Geequlim** [comment]
The crash shoud be fixed by 5010763

**Comment by BracerJack** [comment]
Where can I download the recompiled release ? Thanks.

**Comment by Geequlim** [comment]
You have to build it yourself or wait next pre-release.
