### ISSUE TITLE
prefer package.json + node_modules to current godot.d.ts generation workflow

### ISSUE THREAD

**Issue by MichaelBelousov** [GodotExplorer/ECMAScript#29]
Imo, more idiomatic typescript development (this might change with deno) practices call for the `godot.d.ts` and `decorators.ts` files to be a dependency, rather than generated by the editor. A combination of both could work, but I think the current workflow:

> Run the menu command Project > Tools > ECMAScript > Generate TypeScript Project from the godot editor to generate a TypeScript project

would be better done by generating a `package.json` that depends on some `godot-ecmascript` package on npm that would be maintained by this group.

I wouldn't mind contributing this, but I think it warrants discussion.

Other benefits I can think of:
- versioning the godot binding types
- updating the godot binding types without updating the ECMAScript engine module
- can use a npm-style project's .gitignore, in my project using this (awesome) binding set, I manually ignore the generated files because I prefer it that way

**Comment by Geequlim** [comment]
The `godot.d.ts` and `enumerations.jsx` is generated from the godot ClassDB. It can make sure the generated API always be correct to the current version of engine's API.

**Comment by MichaelBelousov** [comment]
you're right. I wanna say you could use a `file:` version dependency, but I think it's fine as is. I'll close this. Thank you!
