### ISSUE TITLE
add generic argument for cast for get_node 

### ISSUE THREAD

**Issue by MichaelBelousov** [GodotExplorer/ECMAScript#32]
Similar to C#'s `GetNode<Label>()`, add a generic argument to the `$` and `get_node` types.

Something like:
```ts

interface Node {
  $<T extends godot.Node>(path: string): T;
}
```

If there's no reason against it, I could submit a PR once I read up on the repository.

**Comment by Geequlim** [comment]
That looks good to me.
Fell free to make the second way avaliable.
```TypeScript
this.get_node('icon') as godot.Sprite;
this.get_node<godot.Sprite>('icon');
```

**Comment by MichaelBelousov** [comment]
I'll submit a PR soon and close this after

**Comment by MichaelBelousov** [comment]
there are a few other places I'd consider contributing stronger generics, I'll make a PR hopefully soon, I am still converting my current codebase into typescript from C#, after which I can make a PR and close this issue

**Comment by Geequlim** [comment]
You can using `this.get_node(godot.Sprite)` to get first Sprite childe.
For `get_node(path: string)` I'd like to suggest following the typescript style guide.
Using
```ts
this.get_node('icon') as godot.Sprite;
```

instead of 
```ts
this.get_node<godot.Sprite>('icon');
```

**Comment by MichaelBelousov** [comment]
You're right. It should probably just stay as is, closing.
