### ISSUE TITLE
typescript doesn't understand the quickjs operator overloads for godot algebraic types

### ISSUE THREAD

**Issue by MichaelBelousov** [GodotExplorer/ECMAScript#33]
the following code yields an error:
```ts
const a = new godot.Vector2(1, 1);
const b = new godot.Vector2(1, 1);
const c = a + b;
```
The error is:
```
Argument of type 'number' is not assignable to parameter of type 'Vector2'.ts(2345)
```
it can be avoided like so:
```ts
const c = ((a as any) + (b as any) as any as godot.Vector2);
```
is there anyway to avoid this in typescript?

**Comment by MichaelBelousov** [comment]
I suppose the best thing to do in typescript land would be use the explicit godotscript methods over the operators.

**Comment by MichaelBelousov** [comment]
one potential solution is monkey patching some add/sub functions into the godot.Vector2 prototype. But that might not be performant. Another is to fork the typescript compiler 😂 . Although perhaps it's worth making an issue with them about supporting quickJS's quirky operator overloading...

**Comment by Geequlim** [comment]
Add `//@ts-ignore` uppon the line of code using operators

**Comment by MichaelBelousov** [comment]
after looking at several typescript issues, ts-ignore is the way to go, typescript will never support quickjs's non-standard quirk.

**Comment by Geequlim** [comment]
We can provide feedback and this use case to TypeScript upstream. Let TypeScript be able to allow this kind of syntax or be able to disable this kind of error reporting. Unfortunately, my English may not be understood by others.

**Comment by MichaelBelousov** [comment]
it's no problem, I was considering making an issue on TS, i might still, but after reading related issues on their repo I think it's unlikely that they'll want to support a non-standard feature that only quickJS supports. ts-ignore is recommended for such edge cases so I think you're right and decided to close the issue.
