### ISSUE TITLE
Thoughts on prebuilt binaries

### ISSUE THREAD

**Issue by Flux159** [GodotExplorer/ECMAScript#36]
Hi, do you have thoughts on providing prebuilt binaries of Godot with the ECMAScript module already installed?

Specifically, making the builds as mentioned in the README
```
Compilation
Clone the source code of godot
Clone this module and put it into godot/modules/ and make sure the folder name of this module is ECMAScript
Recompile the godot engine (Only MinGW is supported on Windows for now!)
```

is a significant burden to getting started with the project (not to mention making binaries w/out tools for exporting published games). I was wondering if it makes sense to provide prebuilt binaries (or setup a CI/CD pipeline with Github Actions to build & publish them as part of the repo).

**Comment by Geequlim** [comment]
>  I was wondering if it makes sense to provide prebuilt binaries (or setup a CI/CD pipeline with Github Actions to build & publish them as part of the repo).
Yes that make sense.
I can only develop this project in my spare time, so I hope to spend time on improving and optimizing it. I would appreciate it if anyone could provide similar help.
