### ISSUE TITLE
Input.is_action_pressed("ui_right") not triggering

### ISSUE THREAD

**Issue by BracerJack** [GodotExplorer/ECMAScript#38]
_physics_process(delta)
	{
		if (Input.is_action_pressed("ui_right"))
		{
			console.log("Right Pressed !");
		}
	}

**Comment by Yaft** [comment]
Для доступа к методам godot необходимо обращаться к глобальной переменной "godot" 
`godot.Input.is_action_pressed("ui_right")`

**Comment by BracerJack** [comment]
Hello Yaft:
	if (godot.Input.is_action_pressed("ui_right"))
		{
			console.log("Right Pressed !");
		}
It doesn't work, it didn't print otu anything in console, I also double checked project settings->Input Map, everything there checks out.

**Comment by Yaft** [comment]
Perhaps this small [example](https://github.com/GodotExplorer/ECMAScript/files/4962875/topdown_test.zip) will help you. I don't claim to be good quality, but it works. This example is focused on working with a camera for a double stick topdown shooter, like a "hotline miami". This works on  gamepad and hasn't been adapted for keyboard and mouse
