### ISSUE TITLE
Windows builds broken due to quickjs_debugger

### ISSUE THREAD

**Issue by Flux159** [GodotExplorer/ECMAScript#42]
As mentioned in #41 windows (mingw) builds are broken on master due to quickjs_debugger using sys/socket.h

**Comment by Geequlim** [comment]
Hi @Flux159 , Thanks for your contribution !

I'm busy in these days. Will find some time to fix this by implement the quickjs debugger transport in godot TCP api.

**Comment by Flux159** [comment]
No rush, I'm on macOS & most people not compiling from master can use prebuilt binaries :). 

Thanks for the great project btw!

**Comment by Geequlim** [comment]
Fixed
