### ISSUE TITLE
Are Singleton / Autoload supported ? How ?

### ISSUE THREAD

**Issue by kane-thornwyrd** [GodotExplorer/ECMAScript#44]
Hello the GodotExplorer ECMAScript Team !

First: Thank you, this is awesome !
Second: the question in the title, so "Are Singleton / Autoload supported ? How ?"

Thank you !

**Comment by Geequlim** [comment]
You can reference the autoload demo here
https://github.com/GodotExplorer/ECMAScriptDemos/tree/master/autoload

**Comment by kane-thornwyrd** [comment]
Thank you, sorry, I didn't saw the autoload demo.
I think I'll fork, make a nice README.md and a PR, this will be better for users.
