### ISSUE TITLE
[BUG] object with signal that has more than one connection deletes arguments between the calls

### ISSUE THREAD

**Issue by MichaelBelousov** [GodotExplorer/ECMAScript#46]
I haven't set up a minimal viable reproduction yet, but I have a script class (A) with a signal, and then two nodes (both of class B) connect to the node of class A. When A emits its signal, the first node of class B gets the emitted arguments with the call:
```ts
emit_signal('signal_of_a', {ARGUMENT: "something"})
```
But the second node of class B gets an undefined argument instead, and because the bad argument is never set in QuickJSBinder::call, an uninitialized value is used to index the array of arguments which often leads to segfaults.

I also noticed that it happens while the code is in the JS_Call in QuickJSBinder::call_method, but I'm going to sleep for tonight. I will investigate more later. I have a suspicion since it occurs in the JS runtime that the variant_to_var is missing a reference count or something, but I don't know.

**Comment by Geequlim** [comment]
A simple demo to reproduce is welcomed. It's hard for me to understand such
long English statements.

Michael Belousov <notifications@github.com>于2020年8月13日 周四11:14写道：

**Comment by Geequlim** [comment]
Here is a demo project I tested.
Everything works as expected
```ts
import { signal, gdclass, property } from "./decorators";
console.LOG_OBJECT_TO_JSON = true;
@gdclass
class MyNode extends godot.Control {
	@signal
	test_func: string;
	
	js_method_test() {}

	@property({ default: "Hello Godot Property" })
	string_prop: string;
}

@gdclass
class MyMyNode extends MyNode {
	@signal
	test_func2: string;
};

export default class Control extends godot.Control {

	_ready() {
		var n = new MyMyNode();

		console.log('--------------');
		console.log(n.has_signal('test_func'));
		console.log(n.has_signal('test_func2'));
		console.log(n.string_prop === 'Hello Godot Property');
		console.log(n.has_method('js_method_test'));
		console.log('--------------');
		n.connect('test_func', this.callback1, ['AAA', 'BBB']);
		n.connect('test_func', this.callback2, ['CCC', 'DDD']);
		n.emit_signal('test_func', {a: 'a'}, 2);
		n.emit_signal('test_func', {b: 'b'}, 4);
		console.log('--------------');

		n.free();
	}

	callback1(a, b, c, d) {
		console.log("callback1", a, b, c, d);
	}

	callback2(a, b, c, d) {
		console.log("callback2", a, b, c, d);
	}

}
```

Output content
```
--------------
true
true
true
true
--------------
callback1 {"a":"a"} 2 AAA BBB
callback2 {"a":"a"} 2 CCC DDD
callback1 {"b":"b"} 4 AAA BBB
callback2 {"b":"b"} 4 CCC DDD
--------------
```

**Comment by MichaelBelousov** [comment]
I'll try making a reproduction tomorrow, I couldn't do it minimally either so maybe it's something else. But I do have some strange behavior going on...

**Comment by MichaelBelousov** [comment]
Alright I did it tonight instead :). This is a weird one. Check out this reproduction code:
A.jsx
```ts
import B from "./B.jsx";
export default class A extends godot.Node2D {
	static my_signal = "my_signal";
	_ready() {
		this.add_child(new B());
		this.add_child(new B());
		this.emit_signal(A.my_signal, {a: new godot.Vector2(5, 5)});
	}
}
godot.register_signal(A, A.my_signal);
```
B.jsx
```ts
import A from "./A.jsx";
export default class B extends godot.Node2D {
    _ready() {
        this.material = new godot.ShaderMaterial();
        this.$("..").connect(A.my_signal, obj => {
            godot.print(obj);
            this.material.set_shader_param('color', new godot.Color(1,1,0,0.5));
        });
    }
}
```
Basic scene for running script A:
```tscn
[gd_scene load_steps=2 format=2]

[ext_resource path="res://A.jsx" type="Script" id=1]

[node name="Root" type="Node2D"]
script = ExtResource( 1 )
```
Output:
```
{a:(5, 5)}
Null
```
So on the second call it receives `null`. I haven't yet tested for a less specific reproduction,  but I can tomorrow if you don't figure it out by then :)

**Comment by Geequlim** [comment]
@MichaelBelousov  Your code contains cycle import whic should not work

**Comment by MichaelBelousov** [comment]
but it does. You can remove the cycle like this:
```ts
//import A from "./A.jsx";
export default class B extends godot.Node2D {
  _ready() {
    this.material = new godot.ShaderMaterial();
    this.$("..").connect("my_signal", (obj) => {
      this.material.set_shader_param("color", new godot.Color(1, 1, 0, 0.5));
      godot.print(obj);
    });
  }
}
//# sourceMappingURL=TestB.jsx.map
```

**Comment by Geequlim** [comment]
Still can't reproduce.
You'd better provide an demo project

Michael Belousov <notifications@github.com>于2020年8月15日 周六10:00写道：

**Comment by MichaelBelousov** [comment]
Here's my minimal demo:
[ecmascript-multisignal-mvr.zip](https://github.com/GodotExplorer/ECMAScript/files/5078097/ecmascript-multisignal-mvr.zip)
It produces:
```
Godot Engine v3.2.3.beta.custom_build.9e4e83738 - https://godotengine.org
OpenGL ES 3.0 Renderer: Quadro P2000/PCIe/SSE2
 
{a:(5, 5)}
Null
```
on my system. If you can't reproduce, maybe I should try rebasing on a different version of godot and see if that fixes it? Also I have one other module in my local engine source.

**Comment by Geequlim** [comment]
@MichaelBelousov Thank your for reporting the bug and provide the demo project. This issue is fixed now :)

**Comment by MichaelBelousov** [comment]
Thank you! awesome work!
