### ISSUE TITLE
godot.Input.MOUSE_MODE_CONFINED is undefined (probably all enum members)

### ISSUE THREAD

**Issue by MichaelBelousov** [GodotExplorer/ECMAScript#49]
given the following code:
```ts
export default class A extends godot.Node2D {
  _ready() {
    console.log(godot.Input.MOUSE_MODE_CONFINED) // logs undefined
    console.log(godot.Input.MouseMode) // logs undefined
    godot.Input.set_mouse_mode(godot.Input.MOUSE_MODE_CONFINED)
  }
}
```
you can see that both the enum which typescript expects, as wells as the enum constants on the `godot.Input` class itself are undefined. The equivalent gdscript works:
```gdscript
extends Node
class_name A

func _ready():
  print(Input.MOUSE_MODE_CONFINED)  // prints 3
  Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
```

Here is a project containing the scripts:
[ecmascript-mouse-mode-confined.zip](https://github.com/GodotExplorer/ECMAScript/files/5080949/ecmascript-mouse-mode-confined.zip)

If the enum is not intended to be supported by the JS runtime, just typescript types, I would recommend making it a typescript [const enum](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums) which would be replaced by `3` at typescript compile time so the JS runtime only needs to be aware of `godot.Input.MOUSE_MODE_*` not both that and  `godot.Input.MouseMode.MOUSE_MODE_*`

**Comment by Geequlim** [comment]
Thanks for your report again !
