### ISSUE TITLE
requiring node module does not work in export

### ISSUE THREAD

**Issue by vonagam** [GodotExplorer/ECMAScript#51]
It works in editor, but once exported does not.

It works in export only with a relative path in `require` call and with "Script Export Mode" as "Text".

**Comment by Geequlim** [comment]
commonjs modules does not suppprt compile to bytecode yet

**Comment by vonagam** [comment]
What about "only with a relative path" part?

**Comment by vonagam** [comment]
I see, one is not expected to export node_modules and has to use come tool that compiles code into ES module(s).
