### ISSUE TITLE
node_modules, gdignore and export

### ISSUE THREAD

**Issue by vonagam** [GodotExplorer/ECMAScript#52]
Currently godot scans and exports all files in node_modules folder, which is no good as it is notorious for becoming big in size. (Typescript folder is more than 50MB.)

There is `.gdignore` for that. Can be added automatically with some script in package.json:
```
"postinstall": "touch ./node_modules/.gdignore"
```
(Should be something else on windows - there is no `touch` there.)

Problem is - it will prevent needed files from being included in export too...

But previous two issues (#50 and #51) make me think that it might be easier to delegate work with node_modules to some other tool.

For example - you create a file `index.js` through which you export all cjs used by godot scripts and then build it with webpack. And you get a single script that contains only requested packages, which then is required by godot scripts with a relative path.

It removes all the problems associated with node_modules.

Thoughts?

**Comment by Geequlim** [comment]
Feel free to using webpack
The node module is mostly for development usage.

**Comment by vonagam** [comment]
I mean that maybe a basic setup/config for some bundler (webpack, rollup or other) can be included with `Generate TypeScript Project`.

Those issues with resolution, ignoring, exporting do apply to every project, they are not project specific.

Or do you think that this is out of scope?

**Comment by Geequlim** [comment]
I think we only need to ensure the functions of the core language binding. As for the use and selection of third-party libraries and tool chains, it should be left to its users. Of course, we can specify the design intent of which features in the document.

For node modules, its design intent is to quickly test third-party libraries, rather than directly releasing them into products. No one wants to bring a huge black hole when the game is released.

**Comment by vonagam** [comment]
For reference, here is a basic rollup config for ECMAScript project:
```js
import globby from 'globby';
import del from 'rollup-plugin-delete';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from '@rollup/plugin-typescript';

const input = {};
for (const file of globby.sync('**/*.{jsx,tsx}', {cwd: './sources'})) {
  input[file.replace(/\.(jsx|tsx)$/, '')] = `sources/${file}`;
}

export default {
  input,
  output: {
    dir: '../js.build',
    entryFileNames: '[name].jsx',
    chunkFileNames: '.chunks/[name]-[hash].js',
    format: 'es',
    sourcemap: true,
    sourcemapExcludeSources: true,
  },
  plugins: [
    del({targets: '../js.build', force: true, runOnce: true}),
    resolve(),
    commonjs(),
    typescript(),
  ],
};
```

For a structure like this to work:
```
js/
  node_modules/
  sources/ - folder with sources
  .gdignore
  package.json
  rollup.config.js
  tsconfig.json
js.build/ - folder with build files which are used by godot 
```

It needs addition of following packages:
```
@rollup/plugin-commonjs
@rollup/plugin-node-resolve
@rollup/plugin-typescript
globby
rollup
rollup-plugin-delete
tslib
```

And in package.json, initial scripts are replaced with those:
```
"watch": "rollup --config --watch",
"compile": "rollup --config"
```
