### ISSUE TITLE
QuickJs vs V8

### ISSUE THREAD

**Issue by caperaven** [GodotExplorer/ECMAScript#55]
Please excuse my ignorance in complexity of these things but I was wonder the following.
Since V8 is in orders of magnitude faster than quickjs, why not use V8 as the js engine?

**Comment by Geequlim** [comment]
1. V8 is too heavy the compiled binary is about 16MB+
2. V8 take too much of memory
3. V8 is complicated to compiled and integrate to godot build system
4. V8 doesn't support operator overloading
5. QuickJS does not slow as you think it is even faster than lua. The jit of V8 is not available on iOS and consoles the performance is the same level.

**Comment by caperaven** [comment]
> 1. V8 is too heavy the compiled binary is about 16MB+
> 2. V8 take too much of memory
> 3. V8 is complicated to compiled and integrate to godot build system
> 4. V8 doesn't support operator overloading
> 5. QuickJS does not slow as you think it is even faster than lua. The jit of V8 is not available on iOS and consoles the performance is the same level.
