### ISSUE TITLE
Godot-language-support

### ISSUE THREAD

**Issue by ShalokShalom** [GodotExplorer/ECMAScript#66]
Feel free to provide information about the current state of the project on this semi-official repository:

https://github.com/Vivraan/godot-lang-support

I am especially interested into the platform support, so about HTML5, mobile and so on. What works, what is tested?

Much fun :🎉

**Comment by AsakuraMizu** [comment]
I have made it to compile on every platform except HTML5 `release_debug` (see #58), but I haven't test them yet
