### ISSUE TITLE
Javascript and GDScript communication

### ISSUE THREAD

**Issue by TwistedTwigleg** [GodotExplorer/ECMAScript#76]
Is there a way to call Javascript functions, defined in an exported class, from GDScript? Currently when I try to call a Javascript function from GDScript, I get the following error:

~~~
Invalid call. Nonexistent function 'function_name_here' in base 'Node (JS_script_name_here.jsx)'
~~~

I am just calling the function using code like `JS_Node.function_name_here()` in GDScript. I have also tried `JS_Node.call("function_name_here")` but it results in the same error. I looked through the demos and the issues on GitHub, but I did not see anything that mentioned how to call a function from GDScript, though its possible I missed something. I thought I may need to bind the function using something like `godot.register_function` but I could not find any examples of how to use such a function, if it exists.

I am using just straight Javascript currently, not TypeScript, if that makes a difference. The build I am using is from this [GitHub action](https://github.com/GodotExplorer/ECMAScript/actions/runs/290984869).
Thanks!

**Comment by Geequlim** [comment]
You can simply just call the function of javascript from gdscript.
If you wan to call GDScript/C# method from JavaScript code.  You have to using `object.call('method')`

**Comment by Geequlim** [comment]
[a.zip](https://github.com/GodotExplorer/ECMAScript/files/5518959/a.zip)
![image](https://user-images.githubusercontent.com/6964556/98707074-9542bc00-23ba-11eb-85ed-e1b1a1d27271.png)
The builtin editor event support code completion for that in GDScript

**Comment by Geequlim** [comment]
Here is [a demo project](https://github.com/GodotExplorer/ECMAScript/files/5518959/a.zip) you can try.

**Comment by TwistedTwigleg** [comment]
Okay, so it is as I would expect. In my testing project, I am getting different results than the demo project provided, but this makes me thing I did something wrong on my end. I will investigate this further, but I think this issue can be safely closed as it seems to be something with my project rather than the module.

Thanks for the quick reply, explanation, and demo project!
