### ISSUE TITLE
less error  information

### ISSUE THREAD

**Issue by 313364973** [GodotExplorer/ECMAScript#80]
the code run with no error tip,it is diffcute to debug. the godot console log has no error at all.

**Comment by lewispollard** [comment]
Could you be a little more specific? Unsure if you mean you want less error information, or more error information.

I can log to the godot Output panel from ecmascript using `console.log`

Or do you mean you get no output when you throw an error? In that case I get an output of a stacktrace with my message at the bottom, in the Debugger panel.

**Comment by 313364973** [comment]
thanks a lot ,i saw the  stacktrace. that  what i need。
