### ISSUE TITLE
scons platform=windows bits=32 error

### ISSUE THREAD

**Issue by sheenli** [GodotExplorer/ECMAScript#87]
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=32
Using MinGW
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  6%] Compiling ==> modules/ECMAScript/quickjs/quickjs_binder.cpp
[  6%] Compiling ==> modules/ECMAScript/quickjs/quickjs_builtin_binder.cpp
[  6%] Compiling ==> modules/ECMAScript/quickjs/quickjs_builtin_binder.gen.cpp
[  6%] Compiling ==> modules/ECMAScript/quickjs/quickjs_worker.cpp
In file included from modules/ECMAScript/quickjs/quickjs_builtin_binder.cpp:4:
modules/ECMAScript/quickjs/quickjs_binder.h: In static member function 'static real_t QuickJSBinder::js_to_number(JSContext*, const JSValue&)':
modules/ECMAScript/quickjs/quickjs_binder.h:238:21: error: cannot convert 'float_t*' {aka 'long double*'} to 'double*'
  238 |   JS_ToFloat64(ctx, &v, p_val);
      |                     ^~
      |                     |
      |                     float_t* {aka long double*}
In file included from modules/ECMAScript/quickjs/quickjs_builtin_binder.h:4,
                 from modules/ECMAScript/quickjs/quickjs_builtin_binder.cpp:1:
modules/ECMAScript/quickjs/quickjs/quickjs.h:685:42: note:   initializing argument 2 of 'int JS_ToFloat64(JSContext*, double*, JSValue)'
  685 | int JS_ToFloat64(JSContext *ctx, double *pres, JSValueConst val);
      |                                  ~~~~~~~~^~~~
In file included from modules/ECMAScript/quickjs/quickjs_worker.h:5,
                 from modules/ECMAScript/quickjs/quickjs_worker.cpp:1:
modules/ECMAScript/quickjs/quickjs_binder.h: In static member function 'static real_t QuickJSBinder::js_to_number(JSContext*, const JSValue&)':
modules/ECMAScript/quickjs/quickjs_binder.h:238:21: error: cannot convert 'float_t*' {aka 'long double*'} to 'double*'
  238 |   JS_ToFloat64(ctx, &v, p_val);
      |                     ^~
      |                     |
      |                     float_t* {aka long double*}
In file included from modules/ECMAScript/quickjs/quickjs_binder.h:5,
                 from modules/ECMAScript/quickjs/quickjs_worker.h:5,
                 from modules/ECMAScript/quickjs/quickjs_worker.cpp:1:
modules/ECMAScript/quickjs/./quickjs/quickjs.h:685:42: note:   initializing argument 2 of 'int JS_ToFloat64(JSContext*, double*, JSValue)'
  685 | int JS_ToFloat64(JSContext *ctx, double *pres, JSValueConst val);
      |                                  ~~~~~~~~^~~~
In file included from modules/ECMAScript/quickjs/quickjs_binder.cpp:1:
modules/ECMAScript/quickjs/quickjs_binder.h: In static member function 'static real_t QuickJSBinder::js_to_number(JSContext*, const JSValue&)':
modules/ECMAScript/quickjs/quickjs_binder.h:238:21: error: cannot convert 'float_t*' {aka 'long double*'} to 'double*'
  238 |   JS_ToFloat64(ctx, &v, p_val);
      |                     ^~
      |                     |
      |                     float_t* {aka long double*}
In file included from modules/ECMAScript/quickjs/quickjs_binder.h:5,
                 from modules/ECMAScript/quickjs/quickjs_binder.cpp:1:
modules/ECMAScript/quickjs/./quickjs/quickjs.h:685:42: note:   initializing argument 2 of 'int JS_ToFloat64(JSContext*, double*, JSValue)'
  685 | int JS_ToFloat64(JSContext *ctx, double *pres, JSValueConst val);
      |                                  ~~~~~~~~^~~~
In file included from modules/ECMAScript/quickjs/quickjs_builtin_binder.gen.cpp:2:
modules/ECMAScript/quickjs/quickjs_binder.h: In static member function 'static real_t QuickJSBinder::js_to_number(JSContext*, const JSValue&)':
modules/ECMAScript/quickjs/quickjs_binder.h:238:21: error: cannot convert 'float_t*' {aka 'long double*'} to 'double*'
  238 |   JS_ToFloat64(ctx, &v, p_val);
      |                     ^~
      |                     |
      |                     float_t* {aka long double*}
In file included from modules/ECMAScript/quickjs/quickjs_binder.h:5,
                 from modules/ECMAScript/quickjs/quickjs_builtin_binder.gen.cpp:2:
modules/ECMAScript/quickjs/./quickjs/quickjs.h:685:42: note:   initializing argument 2 of 'int JS_ToFloat64(JSContext*, double*, JSValue)'
  685 | int JS_ToFloat64(JSContext *ctx, double *pres, JSValueConst val);
      |                                  ~~~~~~~~^~~~
scons: *** [modules/ECMAScript/quickjs/quickjs_worker.windows.tools.32.o] Error 1
modules/ECMAScript/quickjs/quickjs_binder.cpp: In static member function 'static JSValue QuickJSBinder::variant_to_var(JSContext*, Variant)':
modules/ECMAScript/quickjs/quickjs_binder.cpp:250:27: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'unsigned int'} and 'int' [-Wsign-compare]
  250 |    for (uint32_t i = 0; i < arr.size(); i++) {
      |                         ~~^~~~~~~~~~~~
modules/ECMAScript/quickjs/quickjs_binder.cpp: In static member function 'static Variant QuickJSBinder::var_to_variant(JSContext*, JSValue)':
modules/ECMAScript/quickjs/quickjs_binder.cpp:293:28: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'unsigned int'} and 'int' [-Wsign-compare]
  293 |     for (uint32_t i = 0; i < length; i++) {
      |                          ~~^~~~~~~~
scons: *** [modules/ECMAScript/quickjs/quickjs_builtin_binder.windows.tools.32.o] Error 1
modules/ECMAScript/quickjs/quickjs_binder.cpp: In static member function 'static JSValue QuickJSBinder::godot_builtin_function(JSContext*, JSValue, int, JSValue*, int)':
modules/ECMAScript/quickjs/quickjs_binder.cpp:340:17: warning: unused variable binder' [-Wunused-variable]
  340 |  QuickJSBinder *binder = get_context_binder(ctx);
      |                 ^~~~~~
modules/ECMAScript/quickjs/quickjs_binder.cpp: In member function 'JSClassID QuickJSBinder::register_class(const ClassDB::ClassInfo*)':
modules/ECMAScript/quickjs/quickjs_binder.cpp:807:31: warning: comparison with string literal results in unspecified behavior [-Waddress]
  807 |   if (data.jsclass.class_name == "") {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
modules/ECMAScript/quickjs/quickjs_binder.cpp: In member function 'void QuickJSBinder::add_godot_globals()':
modules/ECMAScript/quickjs/quickjs_binder.cpp:1128:20: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
 1128 |  for (int i = 0; i < sizeof(consts) / sizeof(GlobalNumberConstant); i++) {
      |                  ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/ECMAScript/quickjs/quickjs_binder.cpp: In static member function 'static JSValue QuickJSBinder::godot_adopt_value(JSContext*, JSValue, int, JSValue*)':
modules/ECMAScript/quickjs/quickjs_binder.cpp:2344:10: warning: unused variable 'obj' [-Wunused-variable]
 2344 |  Object *obj = value;
      |          ^~~
scons: *** [modules/ECMAScript/quickjs/quickjs_builtin_binder.gen.windows.tools.32.o] Error 1
scons: *** [modules/ECMAScript/quickjs/quickjs_binder.windows.tools.32.o] Error 1
scons: building terminated because of errors.

**Comment by Geequlim** [comment]
should works for godot 3.4
