### ISSUE TITLE
Error in imports cause Godot IDE to crash

### ISSUE THREAD

**Issue by bnolan** [GodotExplorer/ECMAScript#89]
What happens:

If your import is broken and can't be run, the entire godot IDE crashes.

What should happen:

An error should be raised by godot IDE shouldn't crash.

**Comment by lewispollard** [comment]
Do you have an example @bnolan? I haven't experienced this to my knowledge, an error in an imported module prints a message to the debugger panel, and an error in the console panel if an import is missing or broken.

**Comment by bnolan** [comment]
The problem hasn't seemed to reoccur - I'll reopen this issue with a test case if we can replicate.
