### ISSUE TITLE
Use a version of QuickJS that supports MSVC

### ISSUE THREAD

**Issue by bnolan** [GodotExplorer/ECMAScript#90]
Would it be possible to use this build of QuickJS that compiles on MSVC?

https://github.com/c-smile/quickjspp

**Comment by Geequlim** [comment]
The quickjs we are using is forked and modified for better godot
Integration and a simple debugger support is added to it. So it would be no
that easy to replace it.

Ben Nolan <notifications@github.com>于2021年2月25日 周四05:27写道：
